language: php

before_install:
    - export DATABASE="mydatabase"
    - sh -e .travis/scripts/apt-get.sh
    - sh -e .travis/scripts/gem-install.sh "travis-lint"
    - sh -e .travis/scripts/mysql.sh "$DATABASE"
    - sh -e .travis/scripts/sahi-install.sh

before_script:
    - sh -e .travis/scripts/sahi-configure.sh


script:
    - bin/roundup tests/*
    - travis-lint .travis.yml-dist
